# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [1]:
def share_bread(N, K):
    # your code here
    x = int(K/N)
    y = K - x*N
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14)== (4, 2)

## Комментарий:
В задании 1 можно проще сделать: K // N, K % N вернуть. Также есть функция divmod, которой два числа даются и она возвращает сразу такую пару чисел.
Почему это может быть важно? При делении через / мы насильно переходим от целых чисел к числам плавающей точкой (float), у которых в арифметике есть дефекты (попробуйте написать и запустить следующую строку 0.1 + 0.2 == 0.3
должно быть True, ведь математические это так, но будет False), что может повлиять на результат
Целочисленное деление и взятие остатка из целых чисел не выходят, потому работают стабильно;

In [2]:
0.1 + 0.2 == 0.3

False

In [3]:
def share_bread(N, K):
    # your code here
    x = K//N
    y = K % N
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14)== (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [4]:
def leap_year(year):
    # your code here
    if (year % 4 ==0) and (year % 100 != 0):
        text_result = 'YOU SHALL PASS'
    elif (year % 400 == 0):
        text_result = 'YOU SHALL PASS'
    else:
        text_result = 'YOU SHALL NOT PASS'
    return text_result
        
assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [5]:
import math
def amulet_area(a, b, c):
    # your code here
    p = (a + b + c) / 2
    S = math.sqrt(p * (p - a) * (p - b) * (p - c))
    return S

assert amulet_area(3, 4, 5) == 6

## Комментарий:
В задании 3 можно без импорта math сделать.
Достаточно для возведения в степень написать x ** 2 (возведение в квадрат).
Импорт может отнимать время (особенно, если библиотека большая);

In [6]:
#import math
def amulet_area(a, b, c):
    # your code here
    p = (a + b + c) / 2
    S = ((p * (p - a) * (p - b) * (p - c))) ** 0.5
    return S
assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [7]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

In [8]:
def cal_euclidean_norm(a, b):    
    ## Your code here
    distance = np.linalg.norm(a-b)
    return distance
def cal_euclidean(a, b):    
    ## Your code here
    sum_sq = np.sum(np.square(a - b))
    distance = np.sqrt(sum_sq)
    return distance

def cal_manhattan(a, b):    
    ## Your code here
    distance = 0
    for i in range(len(a)):
        distance += abs(a[i] - b[i])
    return distance

def cal_cosine(a, b):    
    ## Your code here
    distance = 1 - (dot(a, b) / (norm(a)*norm(b)))
    return distance

# для проверки
import scipy.spatial.distance as ds
def cal_cosine1(a, b):    
    ## Your code here
    distance =  ds.cosine(a,b)
    return distance

In [9]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean_norm(a, b))
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))
print(cal_cosine1(a, b))

19.79898987322333
19.79898987322333
42
0.7732087512342742
0.7732087512342742


## Комментарий:
В задании 4 можно манхэттенское расстояние вычислить без цикла?
Суть задания в том, чтобы показать, что с векторами в numpy можно и нужно работать без циклов.
Циклы питона медленные. Векторизация операций, которую делает numpy позволяет оптимизировать код.
В данном случае суть та же, что и в евклидовом: берем np.abs от разности векторов (разность будет покоординатной - фишка numpy), затем берем сумме через np.sum;

In [10]:
def cal_manhattan1(a, b):
    ## Your code here
    distance = np.sum(np.abs(a-b))
    return distance

In [11]:
print(cal_manhattan1(a, b))

42


## Комментарий:
В задании 4 можно вычислить косинусное расстояние без np.linalg.norm? Это не совсем базовая функция... Можно прямо по формуле. 2-норма - это корень из суммы квадратов элементов вектора. По сути, это то же, что в евклидовом расстоянии, но без вычитания.
 Ну или можно скалярное произведение взять вектора самого на себя через np.dot и корень из получившегося числа - это и есть норма;

In [12]:
print(norm(a))
print(norm(b))

16.792855623746664
14.966629547095765


In [13]:
def cal_cosine(a, b):
    ## Your code here
    distance = 1 - (np.dot(a, b) / (norm(a)*norm(b)))
    return distance

In [14]:
print(cal_cosine(a, b))

0.7732087512342742


In [15]:
def cal_cosine2(a, b):
    ## Your code here
    distance = 1 - (np.dot(a, b) / (np.sqrt(a.dot(a))* np.sqrt(a.dot(b))))
    return distance
print(cal_cosine2(a, b))

0.550413901933714


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [16]:
my_array = np.random.rand(100) ## Your code here
np.random.seed(0)
my_array = np.random.rand(100)* (1-0)
print(np.max(my_array), np.min(my_array))
print(my_array)

0.9883738380592262 0.004695476192547066
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918
 0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194
 0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
 0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195
 0.6976312  0.06022547 0.66676672 0.67063787 0.21038256 0.1289263
 0.31542835 0.36371077 0.57019677 0.43860151 0.98837384 0.10204481
 0.20887676 0.16130952 0.65310833 0.2532916  0.46631077 0.24442559
 0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517
 0.82099323 0.09710128 0.83794491 0.09609841 0.97645947 0.4686512
 0.97676109 0.60484552 0.73926358 0.03918779 0.28280696 0.12019656
 0.2961402  0.11872772 0.31798318 0.41426299 0.0641475  0.69247212
 0.56660145 0.26538949 0.

## Комментарий:
В задании 5.1 нужно преобразовать массив. Достаточно будет просто найти индекс наибольшего элемента массива через np.argmax и присвоить данному элементу через срез arr[np.argmax(arr)] значение 1. Для минимума так же, но через np.argmin;

In [17]:
print(np.argmax(my_array), np.argmin(my_array))

52 99


In [18]:
my_array[np.argmax(my_array)] = 1
my_array[np.argmin(my_array)] = 0
print(my_array[np.argmax(my_array)])
print(my_array[np.argmin(my_array)])

1.0
0.0


Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [19]:
my_array = np.random.rand(5,6)* (50-0) ## Your code here
selected_column = my_array.max(axis = 0)
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print('----------------------------------------------------------------------------------')
print(selected_column)

Shape:  (5, 6)
Array
[[33.89082684 13.50039866 36.75970111 48.10942726 12.43765718 28.80786672]
 [29.60209656 28.61259529 11.15408163 47.63745058 22.35626893 42.32043362]
 [34.97396377 14.87184754 40.68989099 19.82528704 44.05515986 29.06364363]
 [44.08676809 34.6265795  36.26271399 25.0662191  47.80418174 32.19950996]
 [21.19275243 30.31966071  0.95965992 15.07874083 33.00867687 14.50388036]]
----------------------------------------------------------------------------------
[44.08676809 34.6265795  40.68989099 48.10942726 47.80418174 42.32043362]


## Комментарий:
В задании 5.2 у вас выводится не столбец. Для ответа на задачу нужно найти номер столбца с наибольшим элементом в массиве. Можно найти максимальные элементы для каждого столбца (через np.max с конкретизацией axis, чтобы именно для столбцов считалось), а потом от этого взять np.argmax, чтобы как раз найти номер столбца с наибольшим элементом. Дальше уже взять срез arr[:, num].

In [20]:
my_array1 = np.random.rand(5,6)* (50-0) ## Your code here
print('Shape: ',my_array1.shape)
print('Array')
print(my_array1)

Shape:  (5, 6)
Array
[[30.90077145 21.43843505  6.77370321 14.9141163  28.49824554 29.54363806]
 [28.71626244 32.66004099 32.6051635  21.57092177 44.82732979 18.3780935 ]
 [21.79324626 44.59616775 40.30969945 35.19442918  5.01134437 45.97413069]
 [35.71206498 49.94235033  7.47241523 43.40630287  8.12464673 30.77797821]
 [ 6.19099914 42.40041147 40.36594794 28.45503693 20.35916486  3.45834977]]


In [21]:
print(np.argmax(my_array1))
print(np.argmax(my_array1, axis=0))
print(np.argmax(my_array1, axis=1))

19
[3 3 4 3 1 2]
[0 4 5 1 1]


In [22]:
all_max = np.amax(my_array1,axis = 0)
one_max = np.argmax(all_max)
print(all_max)
print(one_max)
print('---------------------------------------------------------')
print('Номер столбца, содержащий макс. значение: ', one_max)
print('Столбец, содержащий макс. значение: ', my_array1[:, one_max])

[35.71206498 49.94235033 40.36594794 43.40630287 44.82732979 45.97413069]
1
---------------------------------------------------------
Номер столбца, содержащий макс. значение:  1
Столбец, содержащий макс. значение:  [21.43843505 32.66004099 44.59616775 49.94235033 42.40041147]


Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [23]:
def get_unique_rows(X):
    # Your code here
    X_unique = np.unique(X, axis=0)
    return X_unique

In [24]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[5 5 5]
 [4 4 4]
 [4 5 5]
 [5 4 5]
 [5 5 5]
 [5 5 5]
 [4 4 4]
 [4 5 5]
 [4 5 4]
 [4 5 4]]


In [25]:
get_unique_rows(X)

array([[4, 4, 4],
       [4, 5, 4],
       [4, 5, 5],
       [5, 4, 5],
       [5, 5, 5]])